server:
  port: 8080

spring:
  session:
    store-type: none
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/bookdb?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver




### mybatis暂时雪藏
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.javalearning.entity  # 注意：对应实体类的路径


mybatis-plus:
  mapper